In [4]:
import pandas as pd
from io import StringIO

data = """
City	Item	Sub-item	Sales in INR	Month	Year
Mumbai	Towel	Trident	60	Jan	2001
Mumbai	Towel	Welspun	10	Feb	2002
Mumbai	Hankie	Zodiac	70	Jan	2001
Mumbai	Shirt	Peter England	80	Feb	2001
Mumbai	Shirt	Levis	60	Feb	2002
Mumbai	Shirt	Levis	100	Jan	2001
Delhi	Trouser	Peter England	20	Jan	2001
Delhi	Trouser	Color Plus	90	Feb	2002
Delhi	Towel	Trident	30	Mar	2001
Delhi	Hankie	Zodiac	40	Mar	2002
Bangalore	Lower	Arvind Mills	100	Jan	2001
Bangalore	Shawl	Arrow	350	Feb	2002
Bangalore	Towel	Welspun	10	Feb	2002
Bangalore	Hankie	Zodiac	70	Jan	2001
"""

# Convert the string to a file-like object
data_file = StringIO(data)
df = pd.read_csv(data_file, sep="\t")
df

         City     Item       Sub-item  Sales in INR Month  Year
0      Mumbai    Towel        Trident            60   Jan  2001
1      Mumbai    Towel        Welspun            10   Feb  2002
2      Mumbai   Hankie         Zodiac            70   Jan  2001
3      Mumbai    Shirt  Peter England            80   Feb  2001
4      Mumbai    Shirt          Levis            60   Feb  2002
5      Mumbai    Shirt          Levis           100   Jan  2001
6       Delhi  Trouser  Peter England            20   Jan  2001
7       Delhi  Trouser     Color Plus            90   Feb  2002
8       Delhi    Towel        Trident            30   Mar  2001
9       Delhi   Hankie         Zodiac            40   Mar  2002
10  Bangalore    Lower   Arvind Mills           100   Jan  2001
11  Bangalore    Shawl          Arrow           350   Feb  2002
12  Bangalore    Towel        Welspun            10   Feb  2002
13  Bangalore   Hankie         Zodiac            70   Jan  2001

In [65]:
df[df.City=="Mumbai"].iloc[[0]]

     City   Item Sub-item  Sales in INR Month  Year
0  Mumbai  Towel  Trident            60   Jan  2001

In [66]:
df[df.City=="Mumbai"].iloc[[-1]]

     City   Item Sub-item  Sales in INR Month  Year
5  Mumbai  Shirt    Levis           100   Jan  2001

In [51]:
df[df.City=="Mumbai"].head(1)

     City   Item Sub-item  Sales in INR Month  Year
0  Mumbai  Towel  Trident            60   Jan  2001

In [63]:
df[df.City=="Mumbai"].tail(1)

     City   Item Sub-item  Sales in INR Month  Year
5  Mumbai  Shirt    Levis           100   Jan  2001

In [54]:
df[df['City'] == 'Mumbai'][:1]

     City   Item Sub-item  Sales in INR Month  Year
0  Mumbai  Towel  Trident            60   Jan  2001

In [62]:
df[df['City'] == 'Mumbai'][-1:]

     City   Item Sub-item  Sales in INR Month  Year
5  Mumbai  Shirt    Levis           100   Jan  2001

In [59]:
df.query("City == 'Mumbai'").iloc[[0]]

     City   Item Sub-item  Sales in INR Month  Year
0  Mumbai  Towel  Trident            60   Jan  2001

In [60]:
df.query("City == 'Mumbai'").iloc[[-1]]

     City   Item Sub-item  Sales in INR Month  Year
5  Mumbai  Shirt    Levis           100   Jan  2001

In [55]:
df.query("City == 'Mumbai'").iloc[:1]

     City   Item Sub-item  Sales in INR Month  Year
0  Mumbai  Towel  Trident            60   Jan  2001

In [58]:
df.query("City == 'Mumbai'").iloc[[-1]]

     City   Item Sub-item  Sales in INR Month  Year
5  Mumbai  Shirt    Levis           100   Jan  2001

In [79]:
for i in df.City.unique():
    print(df[df.City==i][:1])
    print(df[df.City==i][-1:])

     City   Item Sub-item  Sales in INR Month  Year
0  Mumbai  Towel  Trident            60   Jan  2001
     City   Item Sub-item  Sales in INR Month  Year
5  Mumbai  Shirt    Levis           100   Jan  2001
    City     Item       Sub-item  Sales in INR Month  Year
6  Delhi  Trouser  Peter England            20   Jan  2001
    City    Item Sub-item  Sales in INR Month  Year
9  Delhi  Hankie   Zodiac            40   Mar  2002
         City   Item      Sub-item  Sales in INR Month  Year
10  Bangalore  Lower  Arvind Mills           100   Jan  2001
         City    Item Sub-item  Sales in INR Month  Year
13  Bangalore  Hankie   Zodiac            70   Jan  2001

In [72]:
df[df.City=="Mumbai"]["Item"].value_counts

<bound method IndexOpsMixin.value_counts of 0     Towel
1     Towel
2    Hankie
3     Shirt
4     Shirt
5     Shirt
Name: Item, dtype: object>

In [24]:
for i in df["City"].unique():
    print(df[df.City==i]["Item"].value_counts)

<bound method IndexOpsMixin.value_counts of 0     Towel
1     Towel
2    Hankie
3     Shirt
4     Shirt
5     Shirt
Name: Item, dtype: object>
<bound method IndexOpsMixin.value_counts of 6    Trouser
7    Trouser
8      Towel
9     Hankie
Name: Item, dtype: object>
<bound method IndexOpsMixin.value_counts of 10     Lower
11     Shawl
12     Towel
13    Hankie
Name: Item, dtype: object>

In [100]:
data = """
Student	Math	Science	English
Alexander Chung	52	95	75
Conner Ashley	60	99	72
Chloe Robertson	41	80	68
Mark Holland	38	82	65
Alyssa Ross	49	75	70
Ethan Taylor	52	85	78
"""
data_file = StringIO(data)
d = pd.read_csv(data_file, sep="\t")
d

           Student  Math  Science  English
0  Alexander Chung    52       95       75
1    Conner Ashley    60       99       72
2  Chloe Robertson    41       80       68
3     Mark Holland    38       82       65
4      Alyssa Ross    49       75       70
5     Ethan Taylor    52       85       78

In [104]:
d[['firstname','lastname']] = d.Student.str.split(" ", expand=True)

In [105]:
d

           Student  Math  Science  English  firstname   lastname
0  Alexander Chung    52       95       75  Alexander      Chung
1    Conner Ashley    60       99       72     Conner     Ashley
2  Chloe Robertson    41       80       68      Chloe  Robertson
3     Mark Holland    38       82       65       Mark    Holland
4      Alyssa Ross    49       75       70     Alyssa       Ross
5     Ethan Taylor    52       85       78      Ethan     Taylor